name: Desplegar en GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Verificar archivos
        run: |
          ls -la
          if [ ! -f index.html ]; then
            echo "Error: index.html no encontrado en la raíz"
            exit 1
          fi

      # No necesitamos copiar a /docs ni usar gh-pages, porque ya está configurado para main y /root
      - name: Confirmar publicación
        run: |
          echo "Archivos listos para publicación en GitHub Pages desde main y /root"
